server:
 port: 8089
 servlet:
    context-path: /sicred/app

spring:
  datasource:
    driver-class-name: ${CLIENT_DB_DRIVER:org.h2.Driver}
    url: ${CLIENT_DB_URL:jdbc:h2:mem:sicred-test}
    username: ${CLIENT_DB_USERNAME:sa}
    password: ${CLIENT_DB_PASSWORD:}
      
sicred:
  server-context-path: /${APP_PATH:}
  h2:
    console:
      enabled: true
      path: /h2-console